cursor                  #8bd5ff
cursor_text_color       #000000

url_color               #6ee7b7

visual_bell_color       #bb9af7
bell_border_color       #bb9af7

active_border_color     #7aa2f7
inactive_border_color   #2b313c

foreground              #e6edf3
background              #050608
selection_foreground    #050608
selection_background    #7aa2f7

active_tab_foreground   #e6edf3
active_tab_background   #161b22
inactive_tab_foreground #7d8590
inactive_tab_background #0b0d10

color0                  #0b0d10
color8                  #4b5563

color1                  #f7768e
color9                  #ff9db0

color2                  #9ece6a
color10                 #b9f27c

color3                  #e0af68
color11                 #f5c97f

color4                  #7aa2f7
color12                 #9cc6ff

color5                  #bb9af7
color13                 #d6bcfa

color6                  #7dcfff
color14                 #9be7ff

color7                  #c9d1d9
color15                 #ffffff
