set -g status-bg                          "default"
set -gq @thm_bar_bg                       "default"

set -gq @thm_bg                           "#0c0f14"
set -gq @thm_fg                           "#eef5ff"
set -gq @thm_primary                      "#8bd5ff"
set -gq @thm_inverse_primary              "#1d2d3b"
set -gq @thm_surface_low                  "#070a0e"
set -gq @thm_surface                      "#10141b"
set -gq @thm_surface_variant              "#263447"
set -gq @thm_outline                      "#566678"
set -gq @thm_text_variant                 "#9aa8ba"

set -g status-style                       "bg=default,fg=#{@thm_fg}"
set -g window-active-style                "bg=default,fg=#{@thm_fg}"
