[general]
framerate = 30
bars = 20
autosens = 1

[input]
method = pipewire

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
channels = mono

[smoothing]
noise_reduction = 60
