.pragma library

// Auto-generated by build-theme.sh
// Colors: /home/axosis/.config/themes/gruvbox/quickshell.js

const bg = "#1b1b1b"
const surface = "#1b1b1b"
const surfaceContainerLow = "#212121"
const surfaceContainer = "#292929"
const surfaceContainerHigh = "#323232"
const surfaceContainerHighest = "#454545"
const surfaceTint = "#ebdbb2"
const outlineVariant = "#565656"
const border = "#565656"
const accent = "#fe8019"
const onAccent = "#292929"
const info = "#83a598"
const warning = "#fe8019"
const success = "#b8bb26"
const accentLight = "#2a241e"
const primaryContainer = "#323232"
const onPrimaryContainer = "#fe8019"
const secondaryContainer = "#323232"
const secondaryContainerHover = "#565656"
const onSecondaryContainer = "#fabd2f"
const wsInactive = "#6e6e6e"
const textPrimary = "#ebdbb2"
const textTitle = "#ebdbb2"
const textSecondary = "#d5c4a1"
const textMuted = "#bdae93"
const textDisabled = "#a89984"

// ── Tint ──
const surfaceTintOpacity = 0.015

// ── Typography ──
const fontMono  = "SF Mono "
const fontIcons = "Material Symbols Rounded"

// ── Shape ──
const radiusSmall = 10
const radiusMedium = 16
const radiusLarge = 24
const radiusExtraLarge = 28
const iconButtonSize = 32
