.pragma library

// Auto-generated by build-theme.sh
// Colors: /home/axosis/.config/themes/mocha/quickshell.js

const bg = "#11111b"
const surface = "#11111b"
const surfaceContainerLow = "#1e1e2e"
const surfaceContainer = "#181825"
const surfaceContainerHigh = "#313244"
const surfaceContainerHighest = "#45475a"
const surfaceTint = "#cdd6f4"
const outlineVariant = "#585b70"
const border = "#585b70"
const accent = "#cba6f7"
const onAccent = "#1e1e2e"
const info = "#89b4fa"
const warning = "#fab387"
const success = "#a6e3a1"
const error = "#f38ba8"
const accentLight = "#242031"
const primaryContainer = "#313244"
const onPrimaryContainer = "#cba6f7"
const secondaryContainer = "#313244"
const secondaryContainerHover = "#585b70"
const onSecondaryContainer = "#89b4fa"
const wsInactive = "#6c7086"
const textPrimary = "#cdd6f4"
const textTitle = "#cdd6f4"
const textSecondary = "#bac2de"
const textMuted = "#6c7086"
const textDisabled = "#585b70"

// ── Semantic Aliases ──
const accentText = typeof onAccent !== 'undefined' ? onAccent : '#00161b'
const primaryText = typeof onPrimaryContainer !== 'undefined' ? onPrimaryContainer : '#a8dbe6'
const secondaryText = typeof onSecondaryContainer !== 'undefined' ? onSecondaryContainer : '#c9a8dc'

// ── Tint ──
const surfaceTintOpacity = 0.015

// ── Typography ──
const fontMono  = "SF Mono "
const fontSans  = "Inter"
const fontIcons = "Material Symbols Rounded "

// ── Shape ──
const radiusSmall = 10
const radiusMedium = 16
const radiusLarge = 24
const radiusExtraLarge = 28
const iconButtonSize = 32
