.pragma library

// Auto-generated by build-theme.sh
// Colors: /home/axosis/.config/themes/ryo/quickshell.js

const bg = "rgba(7, 10, 14, 0.62)"
const surface = "rgba(7, 10, 14, 0.62)"
const surfaceContainerLow = "rgba(12, 15, 20, 0.72)"
const surfaceContainer = "rgba(16, 20, 27, 0.82)"
const surfaceContainerHigh = "rgba(26, 32, 42, 0.88)"
const surfaceContainerHighest = "rgba(38, 47, 61, 0.92)"
const surfaceTint = "#eef5ff"
const outlineVariant = "rgba(132, 151, 170, 0.42)"
const border = "rgba(132, 151, 170, 0.42)"
const accent = "#8bd5ff"
const onAccent = "#071017"
const info = "#8bd5ff"
const warning = "#f0b080"
const success = "#8ff0c7"
const accentLight = "#141e26"
const primaryContainer = "rgba(29, 45, 59, 0.86)"
const onPrimaryContainer = "#b9e6ff"
const secondaryContainer = "rgba(48, 36, 65, 0.84)"
const secondaryContainerHover = "#2e3c4d"
const onSecondaryContainer = "#decaff"
const wsInactive = "#8092a1"
const textPrimary = "#eef5ff"
const textTitle = "#eef5ff"
const textSecondary = "#9aa8ba"
const textMuted = "#899cac"
const textDisabled = "rgba(132, 151, 170, 0.42)"

// ── Tint ──
const surfaceTintOpacity = 0.015

// ── Typography ──
const fontMono  = "SF Mono "
const fontIcons = "Material Symbols Rounded "

// ── Shape ──
const radiusSmall = 10
const radiusMedium = 16
const radiusLarge = 24
const radiusExtraLarge = 28
const iconButtonSize = 32
