return {
  "stevearc/conform.nvim",
  opts = {
    formatters_by_ft = {
      javascript = { "prettierd", "prettier" },
      typescript = { "prettierd", "prettier" },
      javascriptreact = { "prettierd", "prettier" },
      typescriptreact = { "prettierd", "prettier" },
      css = { "prettierd", "prettier" },
      html = { "prettierd", "prettier" },
      yaml = { "prettierd", "prettier" },
      markdown = { "prettierd", "prettier" },
      rust = { "rustfmt" },
      go = { "gofmt" },
      c = { "clang-format" },
      cpp = { "clang-format" },
      java = { "google-java-format" },
      python = { "ruff_format", "ruff_organize_imports" },
      qml = { "qmlformat" },
      yml = { "prettier" },
      bash = { "shfmt" },
      lua = { "stylua" },
      toml = { "taplo" },
      sh = { "shfmt" },
    },
  },
}
