#!/usr/bin/env bash
# Build Theme.js from the active theme's quickshell.js
# Called by theme-switcher or manually to apply theme colors.

THEME_DIR=$(grep "dofile" "$HOME/.config/hypr/theme.lua" | sed 's/dofile("\(.*\)")/\1/')
SOURCE="${THEME_DIR%/*}/quickshell.js"
DEST="$HOME/.config/quickshell/theme/Theme.js"

if [ ! -f "$SOURCE" ]; then
    echo "No quickshell.js found for active theme" >&2
    exit 1
fi

{
    echo ".pragma library"
    echo ""
    echo "// Auto-generated by build-theme.sh"
    echo "// Colors: $SOURCE"
    echo ""
    cat "$SOURCE"
    echo ""
    echo "// ── Tint ──"
    echo "const surfaceTintOpacity = 0.015"
    echo ""
    echo "// ── Typography ──"
    echo "const fontMono  = \"SF Mono \""
    echo "const fontIcons = \"Material Symbols Rounded \""
    echo ""
    echo "// ── Shape ──"
    echo "const radiusSmall = 10"
    echo "const radiusMedium = 16"
    echo "const radiusLarge = 24"
    echo "const radiusExtraLarge = 28"
    echo "const iconButtonSize = 32"
} > "$DEST"

# Theme.qml is reactive, so ThemeService applies the palette in the existing
# shell process. Do not touch a QML file here: that would reload the shell.
echo "Built theme data"
