#!/usr/bin/env bash
# Theme palette helper, two modes:
#   build-theme.sh              regenerate Theme.js from the active theme
#   build-theme.sh rows THEME   emit THEME's quickshell.js as key<TAB>value rows
#                               (used by ThemeService for preview/live apply)
set -uo pipefail

if [ "${1:-}" = "rows" ]; then
    theme_name=${2:?usage: build-theme.sh rows THEME}
    case "$theme_name" in ""|*/*|.*) exit 2 ;; esac

    source_file="$HOME/.config/themes/$theme_name/quickshell.js"
    [ -f "$source_file" ] || exit 2

    sed -n 's/^const \([A-Za-z][A-Za-z0-9]*\) = "\(.*\)"$/\1\t\2/p' "$source_file"
    exit 0
fi

THEME_DIR=$(sed -n 's/.*dofile("\(.*\)").*/\1/p' "$HOME/.config/hypr/theme.lua" | head -n1)
SOURCE="${THEME_DIR%/*}/quickshell.js"
DEST="$HOME/.config/quickshell/theme/Theme.js"

if [ ! -f "$SOURCE" ]; then
    echo "No quickshell.js found for active theme" >&2
    exit 1
fi

{
    echo ".pragma library"
    echo ""
    echo "// Auto-generated by build-theme.sh"
    echo "// Colors: $SOURCE"
    echo ""
    cat "$SOURCE"
    echo ""
    echo "// ── Tint ──"
    echo "const surfaceTintOpacity = 0.015"
    echo ""
    echo "// ── Typography ──"
    echo "const fontMono  = \"SF Mono \""
    echo "const fontIcons = \"Material Symbols Rounded \""
    echo ""
    echo "// ── Shape ──"
    echo "const radiusSmall = 10"
    echo "const radiusMedium = 16"
    echo "const radiusLarge = 24"
    echo "const radiusExtraLarge = 28"
    echo "const iconButtonSize = 32"
} > "$DEST"

# Theme.qml is reactive, so ThemeService applies the palette in the existing
# shell process. Do not touch a QML file here: that would reload the shell.
echo "Built theme data"
