# ┬┌─ ┬┌┬┐┌┬┐┬ ┬
# ├┴┐ │ │  │ └┬┘
# ┴ ┴ ┴ ┴  ┴  ┴

# BEGIN_KITTY_THEME
# Dark Pastel
include theme.conf
# include theme.conf
# END_KITTY_THEME


window_padding_width              7
font_family                       JetBrainsMono Nerd Font
font_size                         11.3
rounded_corners                   yes

cursor_shape                      block
cursor_trail                      1
cursor_trail_decay                0.1 0.4
cursor_trail_start_threshold      0

allow_remote_control              yes

scrollbar_handle_opacity          0
scrollbar_track_opacity           0
scrollbar_track_hover_opacity     0


shell                             zsh
url_style                         curly
remember_window_size              no
# confirm_os_window_close         no
shell_integration                 no-cursor
#scrollback_indicator_indicator   0.0

sync_to_monitor                   no
disable_ligatures                 never

# custom_shaders                    water
# custom_shaders                    crt
# custom_shaders                    crt-blue
# custom_shaders                    bloom
# custom_shaders                    cursor-trail-blaze
custom_shaders                    cursor-trail-lightning
# custom_shaders                    dim-inactive-windows
# custom_shaders                    sample
# custom_shaders                    fireworks-rockets
# custom_shaders                    fireworks
# custom_shaders                    focus-highlight
# custom_shaders                    inside-the-matrix
# custom_shaders                    negative
# custom_shaders                    northern-lights
# custom_shaders                    pond-ripple
# custom_shaders                    spot-light
# custom_shaders                    tab-change
# custom_shaders                    tft
# custom_shaders                    underwater
