set -gq @catppuccin_flavour                "dynamic"

set -g status-bg                          "#0b151a"
set -gq @thm_bar_bg                       "#0b151a"

set -gq @thm_bg                           "#0b151a"
set -gq @thm_fg                           "#dae4ec"
set -gq @thm_primary                      "#7ad0ff"
set -gq @thm_inverse_primary              "#222b31"
set -gq @thm_surface_low                  "#131d23"
set -gq @thm_surface                      "#0b151a"
set -gq @thm_surface_variant              "#222b31"
set -gq @thm_outline                      "#3e484f"
set -gq @thm_text_variant                 "#bec8d0"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
