set -gq @catppuccin_flavour                "dynamic"

set -g status-bg                          "#1e100f"
set -gq @thm_bar_bg                       "#1e100f"

set -gq @thm_bg                           "#1e100f"
set -gq @thm_fg                           "#f9dcd9"
set -gq @thm_primary                      "#ffb3ad"
set -gq @thm_inverse_primary              "#362624"
set -gq @thm_surface_low                  "#271817"
set -gq @thm_surface                      "#1e100f"
set -gq @thm_surface_variant              "#362624"
set -gq @thm_outline                      "#554241"
set -gq @thm_text_variant                 "#dbc0be"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
