set -gq @catppuccin_flavour                "dynamic"

set -g status-bg                          "#17111b"
set -gq @thm_bar_bg                       "#17111b"

set -gq @thm_bg                           "#17111b"
set -gq @thm_fg                           "#eadfed"
set -gq @thm_primary                      "#dfb7ff"
set -gq @thm_inverse_primary              "#2e2832"
set -gq @thm_surface_low                  "#1f1923"
set -gq @thm_surface                      "#17111b"
set -gq @thm_surface_variant              "#2e2832"
set -gq @thm_outline                      "#4b4450"
set -gq @thm_text_variant                 "#cec3d1"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
