import QtQuick

Item {
    id: root
    visible: false

    readonly property var entries: [
        { char: "😀", name: "grinning face" },
        { char: "😁", name: "beaming face with smiling eyes" },
        { char: "😂", name: "face with tears of joy" },
        { char: "🤣", name: "rolling on the floor laughing" },
        { char: "😊", name: "smiling face with smiling eyes" },
        { char: "😇", name: "smiling face with halo" },
        { char: "🙂", name: "slightly smiling face" },
        { char: "🙃", name: "upside down face" },
        { char: "😉", name: "winking face" },
        { char: "😍", name: "smiling face with heart eyes" },
        { char: "🥰", name: "smiling face with hearts" },
        { char: "😘", name: "face blowing a kiss" },
        { char: "😗", name: "kissing face" },
        { char: "😋", name: "face savoring food" },
        { char: "😛", name: "face with tongue" },
        { char: "😜", name: "winking face with tongue" },
        { char: "🤪", name: "zany face" },
        { char: "😝", name: "squinting face with tongue" },
        { char: "🤑", name: "money mouth face" },
        { char: "🤗", name: "hugging face" },
        { char: "🤭", name: "face with hand over mouth" },
        { char: "🤫", name: "shushing face" },
        { char: "🤔", name: "thinking face" },
        { char: "🤐", name: "zipper mouth face" },
        { char: "🤨", name: "face with raised eyebrow" },
        { char: "😐", name: "neutral face" },
        { char: "😑", name: "expressionless face" },
        { char: "😶", name: "face without mouth" },
        { char: "😏", name: "smirking face" },
        { char: "😒", name: "unamused face" },
        { char: "🙄", name: "face with rolling eyes" },
        { char: "😬", name: "grimacing face" },
        { char: "🤥", name: "lying face" },
        { char: "😌", name: "relieved face" },
        { char: "😔", name: "pensive face" },
        { char: "😪", name: "sleepy face" },
        { char: "🤤", name: "drooling face" },
        { char: "😴", name: "sleeping face" },
        { char: "😷", name: "face with medical mask" },
        { char: "🤒", name: "face with thermometer" },
        { char: "🤕", name: "face with head bandage" },
        { char: "🤢", name: "nauseated face" },
        { char: "🤮", name: "face vomiting" },
        { char: "🤧", name: "sneezing face" },
        { char: "🥵", name: "hot face" },
        { char: "🥶", name: "cold face" },
        { char: "🥴", name: "woozy face" },
        { char: "😵", name: "dizzy face" },
        { char: "🤯", name: "exploding head" },
        { char: "🤠", name: "cowboy hat face" },
        { char: "🥳", name: "partying face" },
        { char: "🥸", name: "disguised face" },
        { char: "😎", name: "smiling face with sunglasses" },
        { char: "🤓", name: "nerd face" },
        { char: "🧐", name: "face with monocle" },
        { char: "😕", name: "confused face" },
        { char: "😟", name: "worried face" },
        { char: "🙁", name: "slightly frowning face" },
        { char: "😮", name: "face with open mouth" },
        { char: "😯", name: "hushed face" },
        { char: "😲", name: "astonished face" },
        { char: "😳", name: "flushed face" },
        { char: "🥺", name: "pleading face" },
        { char: "😦", name: "frowning face with open mouth" },
        { char: "😧", name: "anguished face" },
        { char: "😨", name: "fearful face" },
        { char: "😰", name: "anxious face with sweat" },
        { char: "😥", name: "sad but relieved face" },
        { char: "😢", name: "crying face" },
        { char: "😭", name: "loudly crying face" },
        { char: "😱", name: "face screaming in fear" },
        { char: "😖", name: "confounded face" },
        { char: "😣", name: "persevering face" },
        { char: "😞", name: "disappointed face" },
        { char: "😓", name: "downcast face with sweat" },
        { char: "😩", name: "weary face" },
        { char: "😫", name: "tired face" },
        { char: "🥱", name: "yawning face" },
        { char: "😤", name: "face with steam from nose" },
        { char: "😡", name: "pouting face" },
        { char: "😠", name: "angry face" },
        { char: "🤬", name: "face with symbols on mouth" },
        { char: "😈", name: "smiling face with horns" },
        { char: "👿", name: "angry face with horns" },
        { char: "💀", name: "skull" },
        { char: "☠️", name: "skull and crossbones" },
        { char: "💩", name: "pile of poo" },
        { char: "🤡", name: "clown face" },
        { char: "👹", name: "ogre" },
        { char: "👺", name: "goblin" },
        { char: "👻", name: "ghost" },
        { char: "👽", name: "alien" },
        { char: "🤖", name: "robot" },
        { char: "😺", name: "grinning cat" },
        { char: "😸", name: "grinning cat with smiling eyes" },
        { char: "😹", name: "cat with tears of joy" },
        { char: "😻", name: "smiling cat with heart eyes" },
        { char: "😼", name: "cat with wry smile" },
        { char: "😽", name: "kissing cat" },
        { char: "🙀", name: "weary cat" },
        { char: "😿", name: "crying cat" },
        { char: "😾", name: "pouting cat" },

        { char: "👋", name: "waving hand" },
        { char: "🤚", name: "raised back of hand" },
        { char: "🖐️", name: "hand with fingers splayed" },
        { char: "✋", name: "raised hand" },
        { char: "🖖", name: "vulcan salute" },
        { char: "👌", name: "ok hand" },
        { char: "🤌", name: "pinched fingers" },
        { char: "🤏", name: "pinching hand" },
        { char: "✌️", name: "victory hand" },
        { char: "🤞", name: "crossed fingers" },
        { char: "🤟", name: "love you gesture" },
        { char: "🤘", name: "sign of the horns" },
        { char: "🤙", name: "call me hand" },
        { char: "👈", name: "backhand index pointing left" },
        { char: "👉", name: "backhand index pointing right" },
        { char: "👆", name: "backhand index pointing up" },
        { char: "🖕", name: "middle finger" },
        { char: "👇", name: "backhand index pointing down" },
        { char: "☝️", name: "index pointing up" },
        { char: "👍", name: "thumbs up" },
        { char: "👎", name: "thumbs down" },
        { char: "✊", name: "raised fist" },
        { char: "👊", name: "oncoming fist" },
        { char: "🤛", name: "left facing fist" },
        { char: "🤜", name: "right facing fist" },
        { char: "👏", name: "clapping hands" },
        { char: "🙌", name: "raising hands" },
        { char: "👐", name: "open hands" },
        { char: "🤲", name: "palms up together" },
        { char: "🤝", name: "handshake" },
        { char: "🙏", name: "folded hands" },
        { char: "✍️", name: "writing hand" },
        { char: "💅", name: "nail polish" },
        { char: "🤳", name: "selfie" },
        { char: "💪", name: "flexed biceps" },
        { char: "🦾", name: "mechanical arm" },
        { char: "🧠", name: "brain" },
        { char: "👀", name: "eyes" },
        { char: "👁️", name: "eye" },
        { char: "👅", name: "tongue" },
        { char: "👄", name: "mouth" },

        { char: "❤️", name: "red heart" },
        { char: "🧡", name: "orange heart" },
        { char: "💛", name: "yellow heart" },
        { char: "💚", name: "green heart" },
        { char: "💙", name: "blue heart" },
        { char: "💜", name: "purple heart" },
        { char: "🖤", name: "black heart" },
        { char: "🤍", name: "white heart" },
        { char: "🤎", name: "brown heart" },
        { char: "💔", name: "broken heart" },
        { char: "❣️", name: "heart exclamation" },
        { char: "💕", name: "two hearts" },
        { char: "💞", name: "revolving hearts" },
        { char: "💓", name: "beating heart" },
        { char: "💗", name: "growing heart" },
        { char: "💖", name: "sparkling heart" },
        { char: "💘", name: "heart with arrow" },
        { char: "💝", name: "heart with ribbon" },
        { char: "💟", name: "heart decoration" },
        { char: "☮️", name: "peace symbol" },
        { char: "✝️", name: "cross" },
        { char: "⭐", name: "star" },
        { char: "🌟", name: "glowing star" },
        { char: "✨", name: "sparkles" },
        { char: "⚡", name: "high voltage" },
        { char: "🔥", name: "fire" },
        { char: "💯", name: "hundred points" },
        { char: "💥", name: "collision" },
        { char: "💫", name: "dizzy" },
        { char: "💦", name: "sweat droplets" },
        { char: "💨", name: "dashing away" },
        { char: "🕳️", name: "hole" },
        { char: "💣", name: "bomb" },
        { char: "💬", name: "speech balloon" },
        { char: "🗨️", name: "left speech bubble" },
        { char: "💭", name: "thought balloon" },
        { char: "💤", name: "zzz" },

        { char: "🐶", name: "dog face" },
        { char: "🐱", name: "cat face" },
        { char: "🐭", name: "mouse face" },
        { char: "🐹", name: "hamster" },
        { char: "🐰", name: "rabbit face" },
        { char: "🦊", name: "fox" },
        { char: "🐻", name: "bear" },
        { char: "🐼", name: "panda" },
        { char: "🐨", name: "koala" },
        { char: "🐯", name: "tiger face" },
        { char: "🦁", name: "lion" },
        { char: "🐮", name: "cow face" },
        { char: "🐷", name: "pig face" },
        { char: "🐸", name: "frog" },
        { char: "🐵", name: "monkey face" },
        { char: "🙈", name: "see no evil monkey" },
        { char: "🙉", name: "hear no evil monkey" },
        { char: "🙊", name: "speak no evil monkey" },
        { char: "🐔", name: "chicken" },
        { char: "🐧", name: "penguin" },
        { char: "🐦", name: "bird" },
        { char: "🐤", name: "baby chick" },
        { char: "🦆", name: "duck" },
        { char: "🦅", name: "eagle" },
        { char: "🦉", name: "owl" },
        { char: "🦇", name: "bat" },
        { char: "🐺", name: "wolf" },
        { char: "🐗", name: "boar" },
        { char: "🐴", name: "horse face" },
        { char: "🦄", name: "unicorn" },
        { char: "🐝", name: "honeybee" },
        { char: "🐛", name: "bug" },
        { char: "🦋", name: "butterfly" },
        { char: "🐌", name: "snail" },
        { char: "🐞", name: "lady beetle" },
        { char: "🐢", name: "turtle" },
        { char: "🐍", name: "snake" },
        { char: "🦎", name: "lizard" },
        { char: "🐙", name: "octopus" },
        { char: "🦑", name: "squid" },
        { char: "🦀", name: "crab" },
        { char: "🐠", name: "tropical fish" },
        { char: "🐟", name: "fish" },
        { char: "🐬", name: "dolphin" },
        { char: "🐳", name: "spouting whale" },
        { char: "🦈", name: "shark" },
        { char: "🐊", name: "crocodile" },

        { char: "🍏", name: "green apple" },
        { char: "🍎", name: "red apple" },
        { char: "🍊", name: "tangerine" },
        { char: "🍋", name: "lemon" },
        { char: "🍌", name: "banana" },
        { char: "🍉", name: "watermelon" },
        { char: "🍇", name: "grapes" },
        { char: "🍓", name: "strawberry" },
        { char: "🫐", name: "blueberries" },
        { char: "🍈", name: "melon" },
        { char: "🍒", name: "cherries" },
        { char: "🍑", name: "peach" },
        { char: "🥭", name: "mango" },
        { char: "🍍", name: "pineapple" },
        { char: "🥥", name: "coconut" },
        { char: "🥝", name: "kiwi fruit" },
        { char: "🍅", name: "tomato" },
        { char: "🍆", name: "eggplant" },
        { char: "🥑", name: "avocado" },
        { char: "🥦", name: "broccoli" },
        { char: "🥕", name: "carrot" },
        { char: "🌽", name: "corn" },
        { char: "🌶️", name: "hot pepper" },
        { char: "🍕", name: "pizza" },
        { char: "🍔", name: "hamburger" },
        { char: "🍟", name: "french fries" },
        { char: "🌭", name: "hot dog" },
        { char: "🥪", name: "sandwich" },
        { char: "🌮", name: "taco" },
        { char: "🌯", name: "burrito" },
        { char: "🍜", name: "steaming bowl" },
        { char: "🍝", name: "spaghetti" },
        { char: "🍣", name: "sushi" },
        { char: "🍤", name: "fried shrimp" },
        { char: "🍦", name: "soft ice cream" },
        { char: "🍩", name: "doughnut" },
        { char: "🍪", name: "cookie" },
        { char: "🎂", name: "birthday cake" },
        { char: "🍰", name: "shortcake" },
        { char: "🍫", name: "chocolate bar" },
        { char: "🍿", name: "popcorn" },
        { char: "☕", name: "hot beverage" },
        { char: "🍵", name: "teacup without handle" },
        { char: "🍺", name: "beer mug" },
        { char: "🍻", name: "clinking beer mugs" },
        { char: "🥂", name: "clinking glasses" },
        { char: "🍷", name: "wine glass" },
        { char: "🍾", name: "bottle with popping cork" },

        { char: "⚽", name: "soccer ball" },
        { char: "🏀", name: "basketball" },
        { char: "🏈", name: "american football" },
        { char: "⚾", name: "baseball" },
        { char: "🎾", name: "tennis" },
        { char: "🏐", name: "volleyball" },
        { char: "🏓", name: "ping pong" },
        { char: "🏸", name: "badminton" },
        { char: "🥊", name: "boxing glove" },
        { char: "🎳", name: "bowling" },
        { char: "⛳", name: "flag in hole" },
        { char: "🎣", name: "fishing pole" },
        { char: "🎯", name: "direct hit" },
        { char: "🎮", name: "video game" },
        { char: "🎲", name: "game die" },
        { char: "🎸", name: "guitar" },
        { char: "🎹", name: "musical keyboard" },
        { char: "🎧", name: "headphone" },
        { char: "🎤", name: "microphone" },
        { char: "🎨", name: "artist palette" },
        { char: "🎬", name: "clapper board" },
        { char: "🏆", name: "trophy" },
        { char: "🥇", name: "gold medal" },
        { char: "🥈", name: "silver medal" },
        { char: "🥉", name: "bronze medal" },

        { char: "🚗", name: "car" },
        { char: "🚕", name: "taxi" },
        { char: "🚌", name: "bus" },
        { char: "🚓", name: "police car" },
        { char: "🚑", name: "ambulance" },
        { char: "🚒", name: "fire engine" },
        { char: "🚲", name: "bicycle" },
        { char: "🛴", name: "kick scooter" },
        { char: "🏍️", name: "motorcycle" },
        { char: "✈️", name: "airplane" },
        { char: "🚀", name: "rocket" },
        { char: "🛸", name: "flying saucer" },
        { char: "🚁", name: "helicopter" },
        { char: "⛵", name: "sailboat" },
        { char: "🚢", name: "ship" },
        { char: "🚂", name: "locomotive" },
        { char: "🗽", name: "statue of liberty" },
        { char: "🗼", name: "tokyo tower" },
        { char: "🏔️", name: "snow capped mountain" },
        { char: "🌋", name: "volcano" },
        { char: "🏕️", name: "camping" },
        { char: "🏖️", name: "beach with umbrella" },
        { char: "🏝️", name: "desert island" },
        { char: "🌍", name: "globe showing europe africa" },
        { char: "🌙", name: "crescent moon" },
        { char: "☀️", name: "sun" },
        { char: "⭐️", name: "star" },
        { char: "☁️", name: "cloud" },
        { char: "🌧️", name: "cloud with rain" },
        { char: "⛈️", name: "cloud with lightning and rain" },
        { char: "❄️", name: "snowflake" },
        { char: "☃️", name: "snowman" },
        { char: "🌈", name: "rainbow" },
        { char: "🎄", name: "christmas tree" },
        { char: "🎃", name: "jack o lantern" },
        { char: "🎆", name: "fireworks" },
        { char: "🎇", name: "sparkler" },
        { char: "🎉", name: "party popper" },
        { char: "🎊", name: "confetti ball" },
        { char: "🎁", name: "wrapped gift" },
        { char: "🏠", name: "house" },

        { char: "💻", name: "laptop" },
        { char: "🖥️", name: "desktop computer" },
        { char: "⌨️", name: "keyboard" },
        { char: "🖱️", name: "computer mouse" },
        { char: "📱", name: "mobile phone" },
        { char: "☎️", name: "telephone" },
        { char: "📷", name: "camera" },
        { char: "🔋", name: "battery" },
        { char: "💡", name: "light bulb" },
        { char: "🔦", name: "flashlight" },
        { char: "🕯️", name: "candle" },
        { char: "📖", name: "open book" },
        { char: "📚", name: "books" },
        { char: "✏️", name: "pencil" },
        { char: "🖊️", name: "pen" },
        { char: "📌", name: "pushpin" },
        { char: "📎", name: "paperclip" },
        { char: "✂️", name: "scissors" },
        { char: "🔒", name: "locked" },
        { char: "🔓", name: "unlocked" },
        { char: "🔑", name: "key" },
        { char: "🔨", name: "hammer" },
        { char: "🛠️", name: "hammer and wrench" },
        { char: "⚙️", name: "gear" },
        { char: "🧲", name: "magnet" },
        { char: "🔬", name: "microscope" },
        { char: "🔭", name: "telescope" },
        { char: "📡", name: "satellite antenna" },
        { char: "💊", name: "pill" },
        { char: "💉", name: "syringe" },
        { char: "🧪", name: "test tube" },
        { char: "🧬", name: "dna" },

        { char: "✅", name: "check mark button" },
        { char: "✔️", name: "check mark" },
        { char: "❌", name: "cross mark" },
        { char: "❎", name: "cross mark button" },
        { char: "➕", name: "plus" },
        { char: "➖", name: "minus" },
        { char: "❓", name: "question mark" },
        { char: "❗", name: "exclamation mark" },
        { char: "⚠️", name: "warning" },
        { char: "🚫", name: "prohibited" },
        { char: "♻️", name: "recycling symbol" },
        { char: "🔁", name: "repeat" },
        { char: "🔀", name: "shuffle" },
        { char: "🔄", name: "counterclockwise arrows" },
        { char: "🆗", name: "ok button" },
        { char: "🆕", name: "new button" },
        { char: "🔝", name: "top arrow" },
        { char: "🔴", name: "red circle" },
        { char: "🟠", name: "orange circle" },
        { char: "🟡", name: "yellow circle" },
        { char: "🟢", name: "green circle" },
        { char: "🔵", name: "blue circle" },
        { char: "🟣", name: "purple circle" },
        { char: "⚫", name: "black circle" },
        { char: "⚪", name: "white circle" },
        { char: "🟥", name: "red square" },
        { char: "🟦", name: "blue square" }
    ]
}
