set -gq @catppuccin_flavour "tokyonight"

set -gq @thm_bg "#13141c"
set -gq @thm_fg "#c0caf5"
set -gq @thm_primary "#7aa2f7"
set -gq @thm_inverse_primary "#3b4261"
set -gq @thm_surface_low "#101014"
set -gq @thm_surface "#13141c"
set -gq @thm_surface_variant "#212535"
set -gq @thm_outline "#373d58"
set -gq @thm_text_variant "#a9b1d6"
set -g status-style "bg=#{@thm_bg},fg=#{@thm_fg}"